version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ishortenthings-back-end"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1835zk61ygyj2"
s3_prefix = "ishortenthings-back-end"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "EnvName=\"prod\""
