AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  ishortenthings

  Sample SAM Template for ishortenthings

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 15
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"
      
Resources:
  IShortenThingsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: my_app/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        IShortenThings:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: "/{proxy+}"
            Method: ANY

  RedirectTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: "Redirects"
      PrimaryKey: 
        Name: "redirect_id"
        Type: "String"
    # Type: AWS::DynamoDB::Table
    # Properties:
    #   TableName: "Redirects"
    #   AttributeDefinitions:
    #     - AttributeName: "RedirectId"
    #       AttributeType: "S"
    #     - AttributeName: "UsesLeft"
    #       AttributeType: "N"
    #     - AttributeName: "CanRickRoll"
    #       AttributeType: "B"
    #     - AttributeName: "UserToken"
    #       AttributeType: "S"
    #   KeySchema:
    #     - AttributeName: "RedirectId"
    #       KeyType: "HASH"
    #   BillingMode: "PAY_PER_REQUEST"

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  IShortenThingsApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  IShortenThingsFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt IShortenThingsFunction.Arn
  IShortenThingsFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt IShortenThingsFunctionRole.Arn
